version: "3.9"
services:
    api:
        build: .
        ports:
            - "8000:80"
            - "8001:443"
        depends_on:
            - db
        command: ["dotnet", "ef", "database update","--context MsDbContext"]
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:80;https://*:443
            - ASPNETCORE_HTTPS_PORT=443 
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - SA_PASSWORD=testTest*
            - MSSQL_DB=VehicleTrackDb
            - MSSQL_USER=sa
            - MSSQL_PASSWORD=testTest*